from __future__ import annotations

"""Arkane export/execution helpers for production connector hardening.

The class keeps skeleton generation separate from actual Arkane execution:
- skeleton generation is always safe and deterministic;
- production execution is opt-in and requires a user-supplied Arkane input or
  reviewed generated input with species/TS log files.
"""

import os
from pathlib import Path
from typing import Any

from hfauto.core.executables import resolve_executable, run_command
from hfauto.core.io import ensure_dir, write_json


def _safe(value: Any, limit: int = 120) -> str:
    return "".join(ch if ch.isalnum() or ch in "_-" else "_" for ch in str(value))[:limit] or "reaction"


class ArkaneEngine:
    name = "arkane"

    def __init__(self, **config: Any):
        self.config = config

    def allow_subprocess(self) -> bool:
        return bool(
            self.config.get("allow_subprocess", False)
            or self.config.get("run_external", False)
            or os.environ.get("HFAUTO_ALLOW_ARKANE") == "1"
            or os.environ.get("HFAUTO_ALLOW_SUBPROCESS") == "1"
        )

    def executable(self) -> str | None:
        explicit = self.config.get("executable")
        return resolve_executable("Arkane.py", explicit) or resolve_executable("arkane", explicit)

    def write_tst_input_skeleton(self, kinetics_records: list[dict[str, Any]], out_dir: str | Path) -> Path:
        arkane_dir = ensure_dir(Path(out_dir) / "arkane")
        path = arkane_dir / "arkane_tst_input.py"
        lines = [
            "# Auto-generated by hfauto Phase 10.",
            "# Skeleton only: production Arkane requires species log files, rotors,",
            "# transitionState(...) blocks, and reviewed reaction labels.",
            "# This file is intended as a controlled starting point, not a final Arkane model.",
            "",
        ]
        for rec in kinetics_records:
            label = _safe(rec.get("reaction_id"))
            lines.extend(
                [
                    f"# reaction_id: {rec.get('reaction_id')}",
                    f"# T_K: {rec.get('T_K')}",
                    f"# delta_G_act_kcal_mol: {rec.get('delta_G_act_kcal_mol')}",
                    f"# k_corrected_s-1: {rec.get('k_corrected_s-1')}",
                    f"# quality_tier: {rec.get('quality_tier')}",
                    f"# kinetics_quality: {rec.get('kinetics_quality')}",
                    f"# species('{label}_RC', 'path/to/reactant.log')",
                    f"# transitionState('{label}_TS', 'path/to/ts.log')",
                    f"# species('{label}_IP', 'path/to/product.log')",
                    f"# reaction(label='{label}', reactants=['{label}_RC'], products=['{label}_IP'], transitionState='{label}_TS')",
                    "",
                ]
            )
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return path

    def write_reaction_stub(self, kinetics_record: dict[str, Any], out_dir: str | Path) -> Path:
        out = ensure_dir(out_dir)
        rid = str(kinetics_record.get("reaction_id", "reaction"))
        safe = _safe(rid)
        path = out / f"{safe}.py"
        text = [
            "# Auto-generated by hfauto Phase 10.",
            "# Review and replace placeholders with actual log files, rotors and species definitions before production Arkane use.",
            f"# reaction_id: {rid}",
            f"# T_K: {kinetics_record.get('T_K')}",
            f"# delta_G_act_kcal_mol: {kinetics_record.get('delta_G_act_kcal_mol')}",
            f"# k_corrected_s-1: {kinetics_record.get('k_corrected_s-1')}",
            "",
            "# species(...) and transitionState(...) blocks intentionally omitted in skeleton mode.",
            "# kinetics('reaction_label')",
        ]
        path.write_text("\n".join(text) + "\n", encoding="utf-8")
        return path

    def write_arkane_stub(self, reaction_records: list[dict[str, Any]], out_dir: str | Path, config: dict[str, Any] | None = None) -> list[dict[str, Any]]:
        out = ensure_dir(out_dir)
        artifacts: list[dict[str, Any]] = []
        for rec in reaction_records:
            rid = str(rec.get("reaction_id"))
            path = self.write_reaction_stub(rec, out)
            artifacts.append({"reaction_id": rid, "path": str(path), "format": "arkane_python_stub"})
        return artifacts

    def production_readiness(self, kinetics_records: list[dict[str, Any]]) -> dict[str, Any]:
        n = len(kinetics_records)
        q45 = sum(1 for r in kinetics_records if r.get("quality_tier") in {"Q4", "Q5"})
        has_logs = bool(self.config.get("species_log_map") or self.config.get("production_input"))
        return {
            "n_reactions": int(n),
            "n_q4_q5": int(q45),
            "has_species_log_map_or_production_input": bool(has_logs),
            "production_arkane_ready": bool(n and q45 == n and has_logs),
            "readiness_note": "Arkane production requires reviewed species/TS log paths and rotors; skeleton inputs are not production kinetics.",
        }

    def maybe_run_external(self, input_path: str | Path, workdir: str | Path) -> dict[str, Any]:
        wd = ensure_dir(workdir)
        input_path = Path(input_path)
        if not self.allow_subprocess():
            return {"arkane_external_executed": False, "arkane_status": "subprocess_not_allowed", "production_arkane_ready": False}
        exe = self.executable()
        if exe is None:
            return {"arkane_external_executed": False, "arkane_status": "executable_not_found", "production_arkane_ready": False}
        if not input_path.exists():
            return {"arkane_external_executed": False, "arkane_status": "input_not_found", "production_arkane_ready": False, "input_path": str(input_path)}
        cmd = [exe, str(input_path.resolve())]
        result = run_command(cmd, wd, timeout_s=int(self.config.get("timeout_s", 86400)), stdout_name="arkane_stdout.txt", stderr_name="arkane_stderr.txt")
        payload = {
            "arkane_external_executed": bool(result.ok),
            "arkane_status": "success" if result.ok else "failed",
            "input_path": str(input_path),
            "command_result": result.to_dict(),
            "production_arkane_ready": bool(result.ok),
        }
        write_json(wd / "arkane_external_summary.json", payload)
        return payload

    def export_and_maybe_run(self, kinetics_records: list[dict[str, Any]], out_dir: str | Path) -> dict[str, Any]:
        arkane_dir = ensure_dir(Path(out_dir) / "arkane")
        skeleton = self.write_tst_input_skeleton(kinetics_records, out_dir)
        production_input = self.config.get("production_input")
        input_for_run = Path(production_input) if production_input else skeleton
        readiness = self.production_readiness(kinetics_records)
        run_meta = self.maybe_run_external(input_for_run, arkane_dir / "run") if bool(self.config.get("run_external", False)) else {"arkane_external_executed": False, "arkane_status": "not_requested"}
        meta = {**readiness, **run_meta, "skeleton_path": str(skeleton), "input_for_run": str(input_for_run)}
        write_json(arkane_dir / "arkane_export_summary.json", meta)
        return meta
