from __future__ import annotations

"""Render scheduler submit scripts and Snakemake profiles without requiring HPC at test time."""

from pathlib import Path
from typing import Any

import pandas as pd

from hfauto.core.io import ensure_dir, write_json

SLURM_HEADER = """#!/usr/bin/env bash
#SBATCH --job-name={job_name}
#SBATCH --cpus-per-task={ncores}
#SBATCH --mem={memory_gb:.0f}G
#SBATCH --time={walltime}
{partition_line}{gpu_line}set -euo pipefail

"""

PBS_HEADER = """#!/usr/bin/env bash
#PBS -N {job_name}
#PBS -l select=1:ncpus={ncores}:mem={memory_gb:.0f}gb
#PBS -l walltime={walltime}
{queue_line}{gpu_line}set -euo pipefail
cd "$PBS_O_WORKDIR"

"""


def _safe_job_name(name: str) -> str:
    return "hf_" + "".join(c if c.isalnum() or c in "_-" else "_" for c in name)[:120]


def render_submit_script(job: dict[str, Any], scheduler: str = "slurm") -> str:
    job_name = _safe_job_name(str(job.get("job_id", "hfauto")))
    ncores = int(job.get("ncores") or 1)
    memory_gb = float(job.get("memory_gb") or 2)
    walltime = str(job.get("walltime") or "01:00:00")
    gpus = int(job.get("gpus") or 0)
    if scheduler == "pbs":
        header = PBS_HEADER.format(
            job_name=job_name,
            ncores=ncores,
            memory_gb=memory_gb,
            walltime=walltime,
            queue_line=f"#PBS -q {job.get('queue')}\n" if job.get("queue") else "",
            gpu_line=f"#PBS -l ngpus={gpus}\n" if gpus else "",
        )
    else:
        header = SLURM_HEADER.format(
            job_name=job_name,
            ncores=ncores,
            memory_gb=memory_gb,
            walltime=walltime,
            partition_line=f"#SBATCH --partition={job.get('partition')}\n" if job.get("partition") else "",
            gpu_line=f"#SBATCH --gres=gpu:{gpus}\n" if gpus else "",
        )
    return header + "\n".join([
        "echo '[hfauto] job started: ' $(date)",
        "echo '[hfauto] job id: " + str(job.get("job_id")) + "'",
        str(job.get("command", "echo no command")),
        "echo '[hfauto] job finished: ' $(date)",
        "",
    ])


def write_submit_scripts(job_plan_csv: str | Path, out_dir: str | Path, scheduler: str = "slurm") -> list[Path]:
    out = ensure_dir(out_dir)
    try:
        df = pd.read_csv(job_plan_csv)
    except pd.errors.EmptyDataError:
        df = pd.DataFrame()
    scripts: list[Path] = []
    for _, row in df.iterrows():
        job = row.to_dict()
        path = out / f"{job.get('job_id')}.{scheduler}.sh"
        path.write_text(render_submit_script(job, scheduler=scheduler), encoding="utf-8")
        scripts.append(path)
    submit_all = out / f"submit_all_{scheduler}.sh"
    if scheduler == "pbs":
        submit_lines = [f"qsub {p.name}" for p in scripts]
    elif scheduler == "local":
        submit_lines = [f"bash {p.name}" for p in scripts]
    else:
        submit_lines = [f"sbatch {p.name}" for p in scripts]
    submit_all.write_text("#!/usr/bin/env bash\nset -euo pipefail\n" + "\n".join(submit_lines) + "\n", encoding="utf-8")
    scripts.append(submit_all)
    return scripts


def write_snakemake_profile(out_dir: str | Path, scheduler: str = "slurm", default_resources: dict[str, Any] | None = None) -> dict[str, Path]:
    out = ensure_dir(out_dir)
    default_resources = default_resources or {"runtime": 60, "mem_mb": 4000, "threads": 1}
    if scheduler == "slurm":
        executor = "slurm"
    elif scheduler == "pbs":
        executor = "cluster-generic"
    else:
        executor = "local"
    config = {
        "executor": executor,
        "jobs": 100,
        "latency-wait": 60,
        "rerun-incomplete": True,
        "keep-going": True,
        "printshellcmds": True,
        "default-resources": default_resources,
    }
    path = out / "config.yaml"
    write_json(out / "profile_manifest.json", {"scheduler": scheduler, "config": config})
    # Snakemake profile is YAML-like; write simple YAML without requiring yaml writer.
    path.write_text("\n".join(f"{k}: {v}" for k, v in config.items()) + "\n", encoding="utf-8")
    return {"config": path, "manifest": out / "profile_manifest.json"}


def write_snakefile_from_job_plan(job_plan_csv: str | Path, out_dir: str | Path) -> Path:
    out = ensure_dir(out_dir)
    df = pd.read_csv(job_plan_csv)
    targets = [str(row.get("output_dir")) + "/manifest.json" for _, row in df.iterrows()]
    rules = [
        "# Auto-generated by hfauto. Review before production use.",
        "rule all:",
        "    input:",
    ]
    rules += [f"        '{t}'," for t in targets]
    for _, row in df.iterrows():
        job_id = str(row.get("job_id"))
        output_manifest = str(row.get("output_dir")) + "/manifest.json"
        command = str(row.get("command", "echo missing command")).replace("'", "'\\''")
        rules += [
            "",
            f"rule {job_id.replace('-', '_')}:",
            f"    output: '{output_manifest}'",
            f"    threads: {int(row.get('ncores') or 1)}",
            "    resources:",
            f"        mem_mb={int(float(row.get('memory_gb') or 2) * 1024)},",
            "    shell:",
            f"        '{command}'",
        ]
    path = out / "Snakefile"
    path.write_text("\n".join(rules) + "\n", encoding="utf-8")
    return path
