from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd

from hfauto.core.io import ensure_dir, write_json


def render_snakemake_scaffold(job_plan: pd.DataFrame, out_dir: str | Path, config: dict[str, Any] | None = None) -> dict[str, str]:
    """Write a scheduler-neutral Snakemake/HPC scaffold for planned jobs.

    This scaffold is deliberately conservative: it does not try to reimplement
    the scientific workflow DAG. It lets operations teams inspect/submit the
    generated job list and stage-specific resource defaults.
    """
    cfg = config or {}
    out = ensure_dir(out_dir)
    plan_path = out / "job_plan.csv"
    job_plan.to_csv(plan_path, index=False)
    snakefile = out / "Snakefile"
    snakefile.write_text(
        """# Auto-generated by hfauto_ops Phase 9.\n# This Snakefile consumes job_plan.csv. Review before production use.\n\nimport pandas as pd\nJOBS = pd.read_csv('job_plan.csv')\n\nrule all:\n    input:\n        expand('done/{job_id}.done', job_id=JOBS.job_id.tolist())\n\nrule hfauto_stage_job:\n    output:\n        touch('done/{job_id}.done')\n    resources:\n        mem_mb=lambda wildcards: int(float(JOBS.loc[JOBS.job_id == wildcards.job_id, 'memory_gb'].iloc[0]) * 1024),\n        threads=lambda wildcards: int(JOBS.loc[JOBS.job_id == wildcards.job_id, 'threads'].iloc[0])\n    shell:\n        \"{JOBS.loc[JOBS.job_id == wildcards.job_id, 'command'].iloc[0]}\"\n""",
        encoding="utf-8",
    )
    profile_dir = ensure_dir(out / "profiles" / "slurm")
    slurm_config = {
        "executor": "slurm",
        "jobs": int(cfg.get("max_parallel_jobs", 50)),
        "default-resources": ["mem_mb=4000", "runtime=60"],
        "latency-wait": 60,
        "rerun-incomplete": True,
        "printshellcmds": True,
    }
    write_json(profile_dir / "config.json", slurm_config)
    submit_sh = out / "submit_slurm_array.sh"
    n = max(len(job_plan), 1)
    submit_sh.write_text(
        f"""#!/usr/bin/env bash
set -euo pipefail
# Auto-generated SLURM array submit helper. Review account/partition settings.
#SBATCH --job-name=hfauto
#SBATCH --array=0-{n-1}
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --time=01:00:00

PLAN=\"${{1:-job_plan.csv}}\"
CMD=$(python - <<'PYCODE'
import os, pandas as pd
plan = pd.read_csv(os.environ.get('PLAN', 'job_plan.csv'))
idx = int(os.environ.get('SLURM_ARRAY_TASK_ID', '0'))
print(plan.iloc[idx]['command'])
PYCODE
)
echo \"$CMD\"
eval \"$CMD\"
""",
        encoding="utf-8",
    )
    submit_sh.chmod(0o755)
    pbs_sh = out / "submit_pbs_array.sh"
    pbs_sh.write_text(
        f"""#!/usr/bin/env bash
# Auto-generated PBS array submit helper. Review queue/account settings.
#PBS -N hfauto
#PBS -J 0-{n-1}
#PBS -l select=1:ncpus=1:mem=2gb
#PBS -l walltime=01:00:00
set -euo pipefail
PLAN=\"${{1:-job_plan.csv}}\"
CMD=$(python - <<'PYCODE'
import os, pandas as pd
plan = pd.read_csv(os.environ.get('PLAN', 'job_plan.csv'))
idx = int(os.environ.get('PBS_ARRAY_INDEX', '0'))
print(plan.iloc[idx]['command'])
PYCODE
)
echo \"$CMD\"
eval \"$CMD\"
""",
        encoding="utf-8",
    )
    pbs_sh.chmod(0o755)
    return {
        "job_plan_csv": str(plan_path),
        "snakefile": str(snakefile),
        "slurm_profile": str(profile_dir / "config.json"),
        "slurm_array_script": str(submit_sh),
        "pbs_array_script": str(pbs_sh),
    }
